## Getting Started

#### First torch import :')

In [95]:
import torch

In [96]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

#### Each of these values is called an `element of the tensor`. The tensor x contains 12 elements.

In [97]:
x.numel()

12

In [98]:
x.shape

torch.Size([12])

In [99]:
X = x.reshape(3, 4)
print(X, '\n')

X1 = x.reshape(3, -1)
print(X1, '\n')

X2 = x.reshape(-1, 4)
print(X2, '\n')

X2.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) 

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) 

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]) 



torch.Size([3, 4])

In [100]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [101]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

#### Tensor with elements drawn from a standard Gaussian (normal) distribution with `mean 0` and `standard deviation 1`.

In [102]:
torch.randn(3, 4)

tensor([[ 1.5866, -0.2719,  0.3391,  0.8831],
        [-0.6267,  0.5610, -0.8423,  0.0073],
        [ 0.9040,  1.5084,  0.0814, -0.5239]])

In [103]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## Indexing and Slicing

In [104]:
print(X)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


In [105]:
X[-1], X[1:3], X[0]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([0., 1., 2., 3.]))

In [106]:
X[1, 2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [107]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## Operations

In [108]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [109]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [110]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print('X:', X)
print('Y:', Y, '\n')
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

X: tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Y: tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]]) 



(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [111]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [112]:
X < Y

tensor([[ True, False,  True, False],
        [False, False, False, False],
        [False, False, False, False]])

In [113]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [114]:
X.sum()

tensor(66.)

## Broadcasting

In [115]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [116]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [117]:
a + b + 1

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [129]:
a1 = torch.arange(6).reshape((2, 3, 1))
b1 = torch.arange(4).reshape((-1, 1, 2))
a1, b1

(tensor([[[0],
          [1],
          [2]],
 
         [[3],
          [4],
          [5]]]),
 tensor([[[0, 1]],
 
         [[2, 3]]]))

In [130]:
a1 + b1

tensor([[[0, 1],
         [1, 2],
         [2, 3]],

        [[5, 6],
         [6, 7],
         [7, 8]]])

## Saving Memory

In [118]:
before = id(Y)
print(before)
Y = Y + X
after = id(Y)
print(after)
after == before

1489346896656
1489346908704


False

In [119]:
Z = torch.zeros_like(Y)
before = id(Z)
print('id(Z):', before)
Z[:] = X + Y
after = id(Z)
print('id(Z):', after)
before == after

id(Z): 1489346908224
id(Z): 1489346908224


True

In [120]:
before = id(X)
X += Y
id(X) == before

True

## Conversion to Other Python Objects

In [121]:
import numpy

In [122]:
A = X.numpy()
B = torch.from_numpy(A)
print("A:", A, "\n")
print("B:", B, "\n")
type(A), type(B)

A: [[ 2.  3.  8.  9.]
 [ 9. 12. 15. 18.]
 [20. 21. 22. 23.]] 

B: tensor([[ 2.,  3.,  8.,  9.],
        [ 9., 12., 15., 18.],
        [20., 21., 22., 23.]]) 



(numpy.ndarray, torch.Tensor)

In [123]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)