### Scalars

In [1]:
import torch

In [15]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
tab = [x + y, x * y, x / y, x**y, x - y, 2*x - 4*y]
tab = map(str, map(float, tab))
print(" | ".join(tab))

5.0 | 6.0 | 1.5 | 9.0 | 1.0 | -2.0


### Vectors

In [17]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [25]:
x[2], x[-1], x[0], x[:2], x[1:], x[::2]

(tensor(2),
 tensor(2),
 tensor(0),
 tensor([0, 1]),
 tensor([1, 2]),
 tensor([0, 2]))

In [42]:
len(x), len(x[:1]), len(x[::2]), len(x[5::])

(3, 1, 2, 0)

In [43]:
x.shape, x[:2].shape

(torch.Size([3]), torch.Size([2]))

### Matrices

In [58]:
A = torch.arange(6).reshape(3, 2)
A, A.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 torch.Size([3, 2]))

In [57]:
A[0], A[1], A[2], A[1:3]

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([[2, 3],
         [4, 5]]))

In [59]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [64]:
A = torch.tensor([[1, 2, 3], [2, 2, 4], [3, 4, 5]])
print(A, '\n')
print(A.T, '\n')
A == A.T

tensor([[1, 2, 3],
        [2, 2, 4],
        [3, 4, 5]]) 

tensor([[1, 2, 3],
        [2, 2, 4],
        [3, 4, 5]]) 



tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### Tensors

In [75]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [76]:
X.shape

torch.Size([2, 3, 4])

In [77]:
X[1], x[1:]

(tensor([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]),
 tensor([1, 2]))

### Basic Properties of Tensor Arithmetic

In [100]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B, A*3, A*B, A**2, A*B == A**2

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]),
 tensor([[ 0.,  3.,  6.],
         [ 9., 12., 15.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]),
 tensor([[True, True, True],
         [True, True, True]]))

In [84]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [90]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print("X:", X, '\n')
a + X, (a * X).shape

X: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) 



(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### Reduction

In [99]:
x = torch.arange(3, dtype=torch.float32)
print("x:", x, '\n')
x, x.sum(), x.mean(), x.median()

x: tensor([0., 1., 2.]) 



(tensor([0., 1., 2.]), tensor(3.), tensor(1.), tensor(1.))

In [101]:
print("A:", A, '\n')
A.shape, A.sum()

A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) 



(torch.Size([2, 3]), tensor(15.))

In [103]:
A.sum(axis=0), A.sum(axis=1), A.sum(axis=0).shape, A.sum(axis=1).shape

(tensor([3., 5., 7.]), tensor([ 3., 12.]), torch.Size([3]), torch.Size([2]))

In [104]:
A.sum(axis=[0, 1]), A.sum(), A.sum(axis=[0, 1]) == A.sum()

(tensor(15.), tensor(15.), tensor(True))