### Scalars

In [3]:
import torch

In [4]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
tab = [x + y, x * y, x / y, x**y, x - y, 2*x - 4*y]
tab = map(str, map(float, tab))
print(" | ".join(tab))

5.0 | 6.0 | 1.5 | 9.0 | 1.0 | -2.0


### Vectors

In [5]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [6]:
x[2], x[-1], x[0], x[:2], x[1:], x[::2]

(tensor(2),
 tensor(2),
 tensor(0),
 tensor([0, 1]),
 tensor([1, 2]),
 tensor([0, 2]))

In [7]:
len(x), len(x[:1]), len(x[::2]), len(x[5::])

(3, 1, 2, 0)

In [8]:
x.shape, x[:2].shape

(torch.Size([3]), torch.Size([2]))

### Matrices

In [9]:
A = torch.arange(6).reshape(3, 2)
A, A.shape

(tensor([[0, 1],
         [2, 3],
         [4, 5]]),
 torch.Size([3, 2]))

In [10]:
A[0], A[1], A[2], A[1:3]

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([[2, 3],
         [4, 5]]))

In [11]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [12]:
A = torch.tensor([[1, 2, 3], [2, 2, 4], [3, 4, 5]])
print(A, '\n')
print(A.T, '\n')
A == A.T

tensor([[1, 2, 3],
        [2, 2, 4],
        [3, 4, 5]]) 

tensor([[1, 2, 3],
        [2, 2, 4],
        [3, 4, 5]]) 



tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### Tensors

In [13]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [14]:
X.shape

torch.Size([2, 3, 4])

In [15]:
X[1], x[1:]

(tensor([[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]),
 tensor([1, 2]))

### Basic Properties of Tensor Arithmetic

In [16]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()  # Assign a copy of A to B by allocating new memory
A, A + B, A*3, A*B, A**2, A*B == A**2

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]),
 tensor([[ 0.,  3.,  6.],
         [ 9., 12., 15.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]),
 tensor([[ 0.,  1.,  4.],
         [ 9., 16., 25.]]),
 tensor([[True, True, True],
         [True, True, True]]))

In [17]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [18]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
print("X:", X, '\n')
a + X, (a * X).shape

X: tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]) 



(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### Reduction

In [19]:
x = torch.arange(3, dtype=torch.float32)
print("x:", x, '\n')
x, x.sum(), x.mean(), x.median()

x: tensor([0., 1., 2.]) 



(tensor([0., 1., 2.]), tensor(3.), tensor(1.), tensor(1.))

In [20]:
print("A:", A, '\n')
A.shape, A.sum()

A: tensor([[0., 1., 2.],
        [3., 4., 5.]]) 



(torch.Size([2, 3]), tensor(15.))

In [21]:
A.sum(axis=0), A.sum(axis=1), A.sum(axis=0).shape, A.sum(axis=1).shape

(tensor([3., 5., 7.]), tensor([ 3., 12.]), torch.Size([3]), torch.Size([2]))

In [22]:
A.sum(axis=[0, 1]), A.sum(), A.sum(axis=[0, 1]) == A.sum()

(tensor(15.), tensor(15.), tensor(True))

In [23]:
A.mean(), A.sum() / A.numel()

(tensor(2.5000), tensor(2.5000))

In [24]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

In [25]:
A

tensor([[0., 1., 2.],
        [3., 4., 5.]])

### Non-Reduction Sum

In [26]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [27]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [28]:
A, sum_A

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 3.],
         [12.]]))

In [29]:
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

### Dot Products

In [30]:
y = torch.ones(3, dtype = torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [36]:
y = torch.ones(3)
torch.dot(x, y), y.dtype

(tensor(3.), torch.float32)

In [37]:
torch.sum(x * y)

tensor(3.)

### Matrix–Vector Products

In [38]:
A, x

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([0., 1., 2.]))

In [42]:
A.shape, x.shape, torch.mv(A, x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

In [44]:
(A@x).shape

torch.Size([2])

### Matrix–Matrix Multiplication

In [47]:
B = torch.ones(3, 4)
A, B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [46]:
torch.mm(A, B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

### Norms

#### Euclidean norm (L2)

In [48]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

#### Manhattan distance (L1)

In [49]:
torch.abs(u).sum()

tensor(7.)

#### Frobenius norm

In [51]:
p = torch.ones((4, 9))
p

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [52]:
torch.norm(torch.ones((4, 9)))

tensor(6.)

### Exercises

In [73]:
A = torch.tensor([[1, 3, 0], [4, 3, 1], [2, 1, 7]])
B = torch.tensor([[5, 4, 11], [2, 1, 1], [0, 3, 1]])
A, B, '', A+B

(tensor([[1, 3, 0],
         [4, 3, 1],
         [2, 1, 7]]),
 tensor([[ 5,  4, 11],
         [ 2,  1,  1],
         [ 0,  3,  1]]),
 '',
 tensor([[ 6,  7, 11],
         [ 6,  4,  2],
         [ 2,  4,  8]]))

In [75]:
A.T, B.T

(tensor([[1, 4, 2],
         [3, 3, 1],
         [0, 1, 7]]),
 tensor([[ 5,  2,  0],
         [ 4,  1,  3],
         [11,  1,  1]]))

In [74]:
A.T + B.T, '', (A+B).T

(tensor([[ 6,  6,  2],
         [ 7,  4,  4],
         [11,  2,  8]]),
 '',
 tensor([[ 6,  6,  2],
         [ 7,  4,  4],
         [11,  2,  8]]))

In [77]:
X, '', len(X)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 '',
 2)

In [80]:
A, A.sum(axis=1)

(tensor([[1, 3, 0],
         [4, 3, 1],
         [2, 1, 7]]),
 tensor([ 4,  8, 10]))

In [81]:
A / A.sum(axis=1)

tensor([[0.2500, 0.3750, 0.0000],
        [1.0000, 0.3750, 0.1000],
        [0.5000, 0.1250, 0.7000]])

In [86]:
X, '', X.sum(dim=0), '', X.sum(dim=1), '', X.sum(dim=2)

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 '',
 tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 '',
 tensor([[12, 15, 18, 21],
         [48, 51, 54, 57]]),
 '',
 tensor([[ 6, 22, 38],
         [54, 70, 86]]))

In [91]:
X = torch.randn(2, 5, 8, 4)
X

tensor([[[[-0.4684, -0.3503,  1.2702,  1.2015],
          [-0.2362, -0.6752,  0.9838,  0.2994],
          [ 1.5941, -1.6956, -1.3122,  0.5760],
          [ 0.0044, -1.1485, -0.4489, -0.1576],
          [-0.5487, -0.5765,  1.7661,  1.4807],
          [ 1.2465,  0.3630, -0.6182,  0.1121],
          [-1.0966, -0.0975, -0.7188,  0.4656],
          [ 0.1965, -1.6149, -0.4270,  0.4277]],

         [[-1.2874,  0.7446,  1.4720, -2.1306],
          [ 0.8256, -2.1208, -0.1135, -0.0866],
          [-1.1541,  2.5001, -0.2778, -0.2408],
          [-0.0098,  0.8760,  0.1343,  1.6375],
          [ 0.6148, -0.9376,  2.3947,  0.2167],
          [ 0.0560,  0.1969,  0.0191, -0.7034],
          [ 0.8913, -0.7536, -1.4846,  0.0078],
          [ 0.5846,  1.2885,  0.9200, -0.1745]],

         [[-0.5188,  0.3380,  0.3542, -0.3597],
          [-1.1561,  1.2129,  1.2120, -2.3189],
          [-1.0916,  1.0528, -0.2474,  1.6370],
          [-0.1108,  0.2557,  0.6564, -1.9177],
          [-2.5998, -0.2965,  0.0779

In [92]:
 torch.linalg.norm(X), torch.linalg.norm(X).shape

(tensor(18.6715), torch.Size([]))

In [93]:
A = torch.randn(100, 200)
B = torch.randn(100, 200)
C = torch.randn(100, 200)
A, '', B, '', C

(tensor([[ 0.7314,  1.0231, -0.7430,  ..., -0.2024,  3.6630,  2.1665],
         [ 1.0069,  1.9057,  0.5576,  ...,  0.3181, -0.0810,  0.1466],
         [-0.2493,  0.0749,  0.5530,  ...,  1.4095,  0.4323,  0.7636],
         ...,
         [ 1.5306, -0.4001,  0.0392,  ..., -1.8417,  0.5411, -0.8721],
         [-0.9206,  0.4799,  0.1926,  ..., -0.0045, -1.5671,  0.7924],
         [ 0.1297, -0.8331, -1.0927,  ...,  0.8603, -0.8928, -0.7375]]),
 '',
 tensor([[ 0.9637,  0.4248,  0.8084,  ..., -1.5316,  0.1586,  0.2248],
         [ 0.8069,  1.0024, -0.5320,  ..., -0.8571, -1.5702, -0.6898],
         [-1.9381,  0.8579,  1.8354,  ..., -0.5677,  0.9170, -0.1439],
         ...,
         [ 0.6619, -0.4379,  0.1226,  ...,  0.0642, -0.6583, -0.2438],
         [ 0.4118,  0.0689, -0.2588,  ...,  1.6821,  0.6171, -0.8699],
         [ 0.2371, -0.3887, -1.6962,  ...,  0.0193, -0.2737, -0.1384]]),
 '',
 tensor([[ 0.4852,  0.5753,  1.1847,  ...,  0.2616,  1.3573,  0.2904],
         [-0.0724,  1.8639,  1.1162

In [102]:
X = torch.stack([A, B, C])
X,'',X.shape

(tensor([[[ 0.7314,  1.0231, -0.7430,  ..., -0.2024,  3.6630,  2.1665],
          [ 1.0069,  1.9057,  0.5576,  ...,  0.3181, -0.0810,  0.1466],
          [-0.2493,  0.0749,  0.5530,  ...,  1.4095,  0.4323,  0.7636],
          ...,
          [ 1.5306, -0.4001,  0.0392,  ..., -1.8417,  0.5411, -0.8721],
          [-0.9206,  0.4799,  0.1926,  ..., -0.0045, -1.5671,  0.7924],
          [ 0.1297, -0.8331, -1.0927,  ...,  0.8603, -0.8928, -0.7375]],
 
         [[ 0.9637,  0.4248,  0.8084,  ..., -1.5316,  0.1586,  0.2248],
          [ 0.8069,  1.0024, -0.5320,  ..., -0.8571, -1.5702, -0.6898],
          [-1.9381,  0.8579,  1.8354,  ..., -0.5677,  0.9170, -0.1439],
          ...,
          [ 0.6619, -0.4379,  0.1226,  ...,  0.0642, -0.6583, -0.2438],
          [ 0.4118,  0.0689, -0.2588,  ...,  1.6821,  0.6171, -0.8699],
          [ 0.2371, -0.3887, -1.6962,  ...,  0.0193, -0.2737, -0.1384]],
 
         [[ 0.4852,  0.5753,  1.1847,  ...,  0.2616,  1.3573,  0.2904],
          [-0.0724,  1.8639,

In [107]:
X[1] == B,'', torch.equal(X[1], B)

(tensor([[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]]),
 '',
 True)